server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    appname: eureka-server
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  freemarker:
    prefer-file-system-access: false
    template-loader-path: classpath:/templates/
  application:
    name: spring-cloud-eureka